/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description An extra display field on a node — a non-pointer scalar (e.g. height=2), shown as a sub-label. */
        VizField: {
            name: string;
            value: string;
        };
        /** @description A node in one animation step. */
        VizNode: {
            id: string;
            label: string;
            /** @description Originating class for an Instance, or a synthetic kind ("cell" / "entry") for a collection member. Drives CSS. */
            kind: string;
            /** @description The object's other scalar fields, surfaced as small sub-labels. */
            meta: components["schemas"]["VizField"][];
            /** @description An array cell's 0-based index; null for instances and dict entries. */
            slot: number | null;
            /** @description Per-object grouping key (Slice 3 auto-dispatch). Empty for hand-curated payloads. */
            cardId: string;
            /** @description Inferred per-card layout (tree-binary, list-single, hashmap, array-1d, …). Empty → fall back to VizGraph.layoutHint. */
            layoutKind: string;
        };
        /** @description A directed edge; label is the field it came from (e.g. "left" / "right"). */
        VizEdge: {
            from: string;
            to: string;
            label: string;
        };
        /** @description A frame-local variable pointing into the structure — drawn as a labelled, role-coloured caret. */
        VizCursor: {
            name: string;
            /** @description id of the node (or cardId, for cardCursor) it references */
            target: string;
            /** @description role colour from MarkerColors; empty until colorizeCursors assigns it */
            color: string;
        };
        /** @description A rich editorial annotation for one animation step — rendered beside the heap card. */
        Annotation: {
            /** @description Tracer event kind — "call" / "line" / "return" / "exception". Drives eyebrow colour. */
            eyebrow: string;
            /** @description short diff summary, rendered in editorial italic */
            title: string;
            /** @description the source line this step executes */
            body: string;
            /** @description Optional href; reserved for future deep links. */
            link: string | null;
        };
        /** @description One local variable in a stack frame — display-ready for the StackFramesPanel (Slice 2). */
        VizLocal: {
            /** @description variable name */
            name: string;
            /** @description inferred type label (int, TreeNode, list, …) */
            typeName: string;
            /** @description display string */
            value: string;
            /** @description true when this var's value differs from the previous step */
            changed: boolean;
        };
        /** @description A stack frame captured at one animation step (Slice 2); innermost frame first. */
        VizFrame: {
            fn: string;
            locals: components["schemas"]["VizLocal"][];
            /** @description true only for the innermost frame (index 0) */
            isActive: boolean;
        };
        /** @description One animation step — the graph state + emphasis + the source line that produced it. */
        VizGraphStep: {
            nodes: components["schemas"]["VizNode"][];
            edges: components["schemas"]["VizEdge"][];
            /** @description Per-node cursors — refs whose target is itself a node. */
            cursor: components["schemas"]["VizCursor"][];
            /** @description Node ids new this step (freshly created / attached) — persistent-layer cue. */
            highlight: string[];
            /** @description Node ids whose display value differs from the previous step — transient-layer cue. */
            changed: string[];
            /** @description Node ids gone since the previous step, re-emitted once so the renderer can fade them. */
            removed: string[];
            annotation: components["schemas"]["Annotation"];
            /** @description 1-based source line, for the code pane */
            line: number;
            /** @description The call stack at this step (Slice 2); innermost first. */
            frames: components["schemas"]["VizFrame"][];
            /** @description Card-level cursors (Slice 4) — target is the cardId, for the ArrowLayer. */
            cardCursor: components["schemas"]["VizCursor"][];
            /** @description Slice 6 — true when only the source line advanced (heap + active-frame locals identical). Always false for step 0. */
            unchanged: boolean;
            /** @description Bespoke-renderer dispatch axis (ADR-0024) — "stack" / "queue" / …. null → generic renderer. */
            structureType: string | null;
        };
        /** @description One traced test case's animation. */
        VizGraph: {
            steps: components["schemas"]["VizGraphStep"][];
            layoutHint: string;
            title: string;
            truncated: boolean;
        };
        /** @description The full payload handed to the D3 renderer — one VizGraph per traced test case. */
        VizCases: {
            cases: components["schemas"]["VizGraph"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
