package codefolio.client.components.cortex

import codefolio.client.components.icons.LucideIcons
import japgolly.scalajs.react.*
import japgolly.scalajs.react.vdom.html_<^.*

/**
 * Renders a pre-rendered D2 SVG with a fullscreen-zoom affordance.
 *
 * The SVG itself is generated by `render.ts` (the D2 WASM engine runs in the markdown pre-pass) and arrives
 * here as raw `<svg>` markup in `Props.svgHtml`. This component owns the inline render + the "Zoom" trigger;
 * the modal — zoom state, keyboard shortcuts, scroll lock, toolbar — is [[DiagramZoom]], shared with
 * [[MermaidBlock]].
 */
object D2Diagram:

  /** `outerHTML` of the pre-rendered D2 SVG, captured by the markdown pipeline. */
  final case class Props(svgHtml: String)

  val Component =
    ScalaFnComponent
      .withHooks[Props]
      .useState(false) // openS — whether the zoom modal is showing
      .render { (props, openS) =>
        <.div(
          <.div(
            ^.className := "diagram group not-prose",
            <.div(^.dangerouslySetInnerHtml := props.svgHtml),
            <.button(
              ^.tpe := "button",
              ^.onClick --> openS.setState(true),
              ^.aria.label := "Open diagram in fullscreen",
              ^.className  := "diagram__zoom-button",
              LucideIcons.Maximize2(LucideIcons.withClass("diagram__zoom-icon")),
              "Zoom"
            )
          ),
          DiagramZoom.Component(
            DiagramZoom.Props(props.svgHtml, openS.value, openS.setState(false))
          )
        )
      }
